name: Deploy to Bluehost

on:
  push:
    branches:
      - main   # أو الفرع اللي عايز تعمل منه نشر

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.BH_KEY }}

      - name: Deploy to Server
        run: |
          ssh -o StrictHostKeyChecking=no -p ${{ secrets.SSH_PORT }} ${{ secrets.BH_USER }}@${{ secrets.BH_HOST }} "
            cd /home/u508368169/public_html/001-Other/Time4en/ &&
            git pull origin main &&
            composer install --no-dev --optimize-autoloader &&
            php artisan migrate --force &&
            php artisan config:cache &&
            php artisan route:cache
          "
