{\rtf1\ansi\ansicpg1252\cocoartf2822
\cocoatextscaling0\cocoaplatform0{\fonttbl\f0\fswiss\fcharset0 Helvetica;}
{\colortbl;\red255\green255\blue255;}
{\*\expandedcolortbl;;}
\paperw11900\paperh16840\margl1440\margr1440\vieww11520\viewh8400\viewkind0
\pard\tx720\tx1440\tx2160\tx2880\tx3600\tx4320\tx5040\tx5760\tx6480\tx7200\tx7920\tx8640\pardirnatural\partightenfactor0

\f0\fs24 \cf0 name: Deploy to Bluehost\
\
on:\
  push:\
    branches:\
      - main   # \uc0\u1571 \u1608  \u1575 \u1604 \u1601 \u1585 \u1593  \u1575 \u1604 \u1604 \u1610  \u1593 \u1575 \u1610 \u1586  \u1578 \u1593 \u1605 \u1604  \u1605 \u1606 \u1607  \u1606 \u1588 \u1585 \
\
jobs:\
  deploy:\
    runs-on: ubuntu-latest\
\
    steps:\
      - name: Checkout code\
        uses: actions/checkout@v3\
\
      - name: Setup SSH\
        uses: webfactory/ssh-agent@v0.7.0\
        with:\
          ssh-private-key: $\{\{ secrets.SSH_KEY \}\}\
\
      - name: Deploy to Server\
        run: |\
          ssh -o StrictHostKeyChecking=no -p $\{\{ secrets.SSH_PORT \}\} $\{\{ secrets.SSH_USER \}\}@$\{\{ secrets.SSH_HOST \}\} "\
            cd /home/u508368169/public_html/001-Other/Time4en/ &&\
            git pull origin main &&\
            composer install --no-dev --optimize-autoloader &&\
            php artisan migrate --force &&\
            php artisan config:cache &&\
            php artisan route:cache\
          "\
}